package foundation_8;

class CatchError {
	public static void main(String[] args) {
		try {

		} catch (Exception e) {
			System.out.println("Exception");
		} catch (ArithmeticException e) {
			System.out.println("ArithmeticException");
		}
 	}
}
